stages:
  - build
  - test      # Ny stage för tester
  - deploy
  - teardown

#############################################
# 1) Bygg backend-imagen
#############################################
build:
  image: docker:20
  stage: build
  before_script:
    - docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - |
      # Sätt DOCKER_TAG till "latest" om main, annars använd branch-namnet
      if [[ $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH ]]; then
        DOCKER_TAG="latest"
      else
        DOCKER_TAG="$CI_COMMIT_REF_NAME"
      fi
      echo "Bygger $CI_REGISTRY_IMAGE:$DOCKER_TAG"
      # Bygg hela Docker-imagen (inte bara base-steget) och pusha till registret
      docker buildx build \
        --cache-from="$CI_REGISTRY_IMAGE:latest" \
        -t "$CI_REGISTRY_IMAGE:$DOCKER_TAG" \
        --push \
        .
  rules:
    - if: $CI_MERGE_REQUEST_ID
      changes:
        - Dockerfile
        - package.json
        - package-lock.json
        - tsconfig.json
        - src/**/*.ts
        - docker-compose.yml
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - Dockerfile
        - package.json
        - package-lock.json
        - tsconfig.json
        - src/**/*.ts
        - docker-compose.yml

#############################################
# 2) Bygg "utils"-imagen
#############################################
build-utils:
  image: docker:20
  stage: build
  before_script:
    - docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - |
      echo "Bygger $CI_REGISTRY_IMAGE/utils:latest"
      docker buildx build \
        --cache-from="$CI_REGISTRY_IMAGE/utils:latest" \
        -t "$CI_REGISTRY_IMAGE/utils:latest" \
        --push \
        -f Dockerfile-utils \
        .
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - Dockerfile-utils

#############################################
# 3) Smoke-test-job (för att stoppa deploy vid fel)
#############################################
test_smoke:
  stage: test
  image: docker:20
  services:
    - docker:20-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - |
      if [[ $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH ]]; then
        DOCKER_TAG="latest"
      else
        DOCKER_TAG="$CI_COMMIT_REF_NAME"
      fi
  script:
    - apk add --no-cache curl
    # Sätt ett unikt container-namn baserat på CI_JOB_ID
    - export CONTAINER_NAME="backend-test-${CI_JOB_ID}"
    # Ta bort eventuell gammal container med samma namn
    - docker rm -f "${CONTAINER_NAME}" || true
    # Dra ner den nyss byggda imagen
    - docker pull "$CI_REGISTRY_IMAGE:$DOCKER_TAG"
    # Starta containern med dynamisk portmappning (-P låter Docker välja en ledig hostport)
    - docker run -d --name "${CONTAINER_NAME}" -P "$CI_REGISTRY_IMAGE:$DOCKER_TAG"
    # Vänta några sekunder så att applikationen hinner starta
    - sleep 5
    # Hämta hostporten som containerport 3000 mappats till, ex:
    - export HOST_PORT=$(docker port "${CONTAINER_NAME}" 3000 | cut -d: -f2)
    - echo "Backend kör på hostport: ${HOST_PORT}"
    # Testa att applikationen svarar på /health via den dynamiska hostporten
    - curl -f http://localhost:${HOST_PORT}/health
    - echo "Smoke test passed! Backend svarar på hälsokoll."
    # Stoppa och rensa upp containern
    - docker rm -f "${CONTAINER_NAME}"
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH




#############################################
# 4) Deploy-job för Merge Requests (review)
#############################################
deploy_review:
  stage: deploy
  image: "$CI_REGISTRY_IMAGE/utils:latest"
  environment:
    name: "review-$CI_COMMIT_REF_NAME"
    url: "https://review-$CI_COMMIT_REF_NAME.cc25.chasacademy.dev"
    on_stop: stop_review
  rules:
    - if: $CI_MERGE_REQUEST_ID
  script:
    - |
      set -e
      # Logga in i Portainer
      export PORTAINER_TOKEN=$(curl -X POST "https://portainer.cc25.chasacademy.dev/api/auth" \
        --json '{"username": "'$PORTAINER_USER'", "password": "'$PORTAINER_PASSWORD'"}' \
        | jq -r '.jwt')
      # Bygg stack-namn med namespace, repo och gren
      export STACK_NAME="$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
      export NORMALIZED_STACK_NAME=$(echo "$STACK_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_-')
      export CI_ENVIRONMENT_SLUG="review-$(echo "$CI_COMMIT_REF_NAME" | tr '[:upper:]' '[:lower:]')"
      export DOCKER_TAG="$CI_COMMIT_REF_NAME"
      echo "STACK: $STACK_NAME"
      echo "NORMALIZED_STACK_NAME: $NORMALIZED_STACK_NAME"
      echo "CI_ENVIRONMENT_SLUG: $CI_ENVIRONMENT_SLUG"
      echo "DOCKER_TAG: $DOCKER_TAG"
      # Generera docker-compose med envsubst
      envsubst < docker-compose.yml > deployable-compose.yml
      cat deployable-compose.yml
      # Hämta endpoint och swarm ID
      export ENDPOINT_ID=$(curl -sSL \
        -H "Authorization: Bearer $PORTAINER_TOKEN" \
        https://portainer.cc25.chasacademy.dev/api/endpoints \
        | jq -r '.[] | select(.Name == "primary") | .Id')
      export SWARM_ID=$(curl -sSL \
        -H "Authorization: Bearer $PORTAINER_TOKEN" \
        https://portainer.cc25.chasacademy.dev/api/endpoints \
        | jq -r '.[] | select(.Name == "primary") | .Snapshots[0].DockerSnapshotRaw.Info.Swarm.Cluster.ID')
      # Kolla om stack redan finns
      STACK_ID=$(curl -sSL \
        -H "Authorization: Bearer $PORTAINER_TOKEN" \
        https://portainer.cc25.chasacademy.dev/api/stacks \
        | jq -r --arg NAME "$NORMALIZED_STACK_NAME" '.[] | select(.Name == $NAME) | .Id')
      # Skapa eller uppdatera stack
      if [ -z "$STACK_ID" ]; then
        echo "Skapar stack $NORMALIZED_STACK_NAME"
        curl -X POST \
          "https://portainer.cc25.chasacademy.dev/api/stacks/create/swarm/file?endpointId=$ENDPOINT_ID" \
          -H "Authorization: Bearer $PORTAINER_TOKEN" \
          -F Name="$NORMALIZED_STACK_NAME" \
          -F SwarmID="$SWARM_ID" \
          -F file=@deployable-compose.yml \
          | jq
      else
        echo "Uppdaterar stack $STACK_ID ($NORMALIZED_STACK_NAME)"
        COMPOSE_CONTENTS=$(cat deployable-compose.yml)
        JSON_PAYLOAD=$(jq -n --arg compose "$COMPOSE_CONTENTS" \
          '{"prune": true, "pullImage": true, "stackFileContent": $compose}')
        curl -X PUT \
          "https://portainer.cc25.chasacademy.dev/api/stacks/$STACK_ID?endpointId=$ENDPOINT_ID" \
          -H "Authorization: Bearer $PORTAINER_TOKEN" \
          --json "$JSON_PAYLOAD" \
          | jq
      fi

#############################################
# 5) Deploy-job för main (production)
#############################################
deploy_main:
  stage: deploy
  image: "$CI_REGISTRY_IMAGE/utils:latest"
  environment:
    name: "production"
    url: "https://vibedrop-backend.cc25.chasacademy.dev"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - |
      set -e
      # Logga in i Portainer
      export PORTAINER_TOKEN=$(curl -X POST "https://portainer.cc25.chasacademy.dev/api/auth" \
        --json '{"username": "'$PORTAINER_USER'", "password": "'$PORTAINER_PASSWORD'"}' \
        | jq -r '.jwt')
      # Bygg stack-namn
      export STACK_NAME="$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
      export NORMALIZED_STACK_NAME=$(echo "$STACK_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_-')
      # För main => hårdkoda domain + Docker-tag
      export CI_ENVIRONMENT_SLUG="vibedrop-backend"
      export DOCKER_TAG="latest"
      echo "STACK: $STACK_NAME"
      echo "NORMALIZED_STACK_NAME: $NORMALIZED_STACK_NAME"
      echo "CI_ENVIRONMENT_SLUG: $CI_ENVIRONMENT_SLUG"
      echo "DOCKER_TAG: $DOCKER_TAG"
      # Generera docker-compose
      envsubst < docker-compose.yml > deployable-compose.yml
      cat deployable-compose.yml
      # Hämta endpoint & swarm
      export ENDPOINT_ID=$(curl -sSL \
        -H "Authorization: Bearer $PORTAINER_TOKEN" \
        https://portainer.cc25.chasacademy.dev/api/endpoints \
        | jq -r '.[] | select(.Name == "primary") | .Id')
      export SWARM_ID=$(curl -sSL \
        -H "Authorization: Bearer $PORTAINER_TOKEN" \
        https://portainer.cc25.chasacademy.dev/api/endpoints \
        | jq -r '.[] | select(.Name == "primary") | .Snapshots[0].DockerSnapshotRaw.Info.Swarm.Cluster.ID')
      # Kolla om stack redan finns
      STACK_ID=$(curl -sSL \
        -H "Authorization: Bearer $PORTAINER_TOKEN" \
        https://portainer.cc25.chasacademy.dev/api/stacks \
        | jq -r --arg NAME "$NORMALIZED_STACK_NAME" '.[] | select(.Name == $NAME) | .Id')
      # Skapa eller uppdatera
      if [ -z "$STACK_ID" ]; then
        echo "Skapar stack $NORMALIZED_STACK_NAME"
        curl -X POST \
          "https://portainer.cc25.chasacademy.dev/api/stacks/create/swarm/file?endpointId=$ENDPOINT_ID" \
          -H "Authorization: Bearer $PORTAINER_TOKEN" \
          -F Name="$NORMALIZED_STACK_NAME" \
          -F SwarmID="$SWARM_ID" \
          -F file=@deployable-compose.yml \
          | jq
      else
        echo "Uppdaterar stack $STACK_ID ($NORMALIZED_STACK_NAME)"
        COMPOSE_CONTENTS=$(cat deployable-compose.yml)
        JSON_PAYLOAD=$(jq -n --arg compose "$COMPOSE_CONTENTS" \
          '{"prune": true, "pullImage": true, "stackFileContent": $compose}')
        curl -X PUT \
          "https://portainer.cc25.chasacademy.dev/api/stacks/$STACK_ID?endpointId=$ENDPOINT_ID" \
          -H "Authorization: Bearer $PORTAINER_TOKEN" \
          --json "$JSON_PAYLOAD" \
          | jq
      fi

#############################################
# 6) Teardown-job för att stoppa review
#############################################
stop_review:
  stage: teardown
  image: "$CI_REGISTRY_IMAGE/utils:latest"
  environment:
    name: "review-$CI_COMMIT_REF_NAME"
    action: stop
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
  script:
    - |
      set -e
      export PORTAINER_TOKEN=$(curl -X POST "https://portainer.cc25.chasacademy.dev/api/auth" \
        --json '{"username": "'$PORTAINER_USER'", "password": "'$PORTAINER_PASSWORD'"}' \
        | jq -r '.jwt')
      export STACK_NAME=$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME
      echo "STACK: $STACK_NAME"
      export ENDPOINT_ID=$(curl -sSL \
        -H "Authorization: Bearer $PORTAINER_TOKEN" \
        https://portainer.cc25.chasacademy.dev/api/endpoints \
        | jq -r '.[] | select(.Name == "primary") | .Id')
      echo "Endpoint: $ENDPOINT_ID"
      NORMALIZED_STACK_NAME=$(echo "$STACK_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_-')
      echo "Kollar om stack $NORMALIZED_STACK_NAME finns..."
      STACK_ID=$(curl -sSL \
        -H "Authorization: Bearer $PORTAINER_TOKEN" \
        https://portainer.cc25.chasacademy.dev/api/stacks \
        | jq -r --arg NAME "$NORMALIZED_STACK_NAME" '.[] | select(.Name == $NAME) | .Id')
      echo "Stack id: \"$STACK_ID\""
      if [ -z "$STACK_ID" ]
      then
        echo "Stack $STACK_ID $STACK_NAME hittades inte!"
        exit 1
      else 
        echo "Tar bort stack $STACK_ID ($STACK_NAME)"
        response=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE \
          "https://portainer.cc25.chasacademy.dev/api/stacks/$STACK_ID?endpointId=$ENDPOINT_ID" \
          -H "Authorization: Bearer $PORTAINER_TOKEN")
        if [ "$response" -eq 204 ]; then
          echo "Stack $STACK_ID raderades framgångsrikt."
        else
          echo "Misslyckades med att ta bort stack $STACK_ID. HTTP-statuskod: $response"
          exit 1
        fi
      fi
